### PR TITLE
Added systemd support

### PR DESCRIPTION
**Pull request by yoav-steinberg**
Added systemd support in debian build (motivation was support for my ubuntu 15.04 machine).

### CODE REVIEW

**Comment by cronner** [comment]
How to build it on  ubuntu 15.04 / debian 8.0 jessie after pulling git and adding the file? :)

**Comment by yoav-steinberg** [comment]
I just built the deb on Ubuntu 15.04: fab assets, fab debian. You can use a VM / container to do the build.

On June 14, 2015 1:20:34 AM GMT+03:00, cronner <notifications@github.com> wrote:
>How to build it on  ubuntu 15.04 / debian 8.0 jessie after pulling git
>and adding the file? :)
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/claudyus/LXC-Web-Panel/pull/82#issuecomment-111755944

-- 
Sent from my mobile.

**Comment by cronner** [comment]
Going to wait until it merges, keeps getting errors :)

**Comment by claudyus** [comment]
Thanks for you PR I will test it on 15.04 VM in the next few days!

Regards

**Comment by cronner** [comment]
lwp starts with this file but when setting limits:

      lxc-start 20150427012246.735 ERROR    lxc_cgmanager - cgmanager.c:cgm_setup_limits:1386 - call to cgmanager_set_value_sync failed: invalid request
      lxc-start 20150427012246.735 ERROR    lxc_cgmanager - cgmanager.c:cgm_setup_limits:1389 - Error setting cgroup memory:lxc/vm1 limit type memory.memsw.limit_in_bytes
      lxc-start 20150427012246.735 ERROR    lxc_start - start.c:lxc_spawn:990 - failed to setup the cgroup limits for 'vm1'
      lxc-start 20150427012246.783 ERROR    lxc_start - start.c:__lxc_start:1172 - failed to spawn 'avs'
      lxc-start 20150427012246.788 ERROR    lxc_start_ui - lxc_start.c:main:344 - The container failed to start.
      lxc-start 20150427012246.788 ERROR    lxc_start_ui - lxc_start.c:main:346 - To get more details, run the container in foreground mode.
      lxc-start 20150427012246.788 ERROR    lxc_start_ui - lxc_start.c:main:348 - Additional information can be obtained by setting the --logfile and --logpriority options.

**Pull request merged**
